version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DSN: postgres://user:password@db:5432/pastebin?sslmode=disable
      REDIS_ADDR: redis:6379

volumes:
  db-data:
