// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/paste": {
            "post": {
                "description": "Создает новую пасту с указанным содержимым и временем истечения. Возвращает ID, hash и короткий URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pastes"
                ],
                "summary": "Создать новую пасту",
                "parameters": [
                    {
                        "description": "Данные пасты",
                        "name": "paste",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreatePasteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.PasteCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/paste/hash/{hash}": {
            "get": {
                "description": "Возвращает пасту по уникальному hash. Также увеличивает счётчик просмотров.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pastes"
                ],
                "summary": "Получить пасту по hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash пасты",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Paste"
                        }
                    },
                    "400": {
                        "description": "Некорректный hash",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Паста не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/paste/popular": {
            "get": {
                "description": "Возвращает список самых просматриваемых паст (по убыванию просмотров)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Получить популярные пасты",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Максимальное количество записей (по умолчанию 5)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Paste"
                            }
                        }
                    },
                    "404": {
                        "description": "Популярные пасты не найдены",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении статистики",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/paste/{id}": {
            "get": {
                "description": "Возвращает полную информацию о пасте по её ID. Также увеличивает счётчик просмотров.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pastes"
                ],
                "summary": "Получить пасту по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пасты",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Paste"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Паста не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет существующую пасту по её уникальному ID",
                "tags": [
                    "pastes"
                ],
                "summary": "Удалить пасту по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пасты",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Паста удалена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Паста не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/shorturl/{hash}": {
            "post": {
                "description": "Создает короткую ссылку по переданному hash пасты. Используется первые 6 символов хэша.",
                "tags": [
                    "shorturls"
                ],
                "summary": "Создать короткий URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hash пасты",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.ShortURL"
                        }
                    },
                    "400": {
                        "description": "Хэш слишком короткий или отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/shorturl/{id}": {
            "get": {
                "description": "Возвращает объект короткой ссылки по её ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shorturls"
                ],
                "summary": "Получить короткий URL по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ShortURL",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ShortURL"
                        }
                    },
                    "400": {
                        "description": "ID отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "ShortURL не найден",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет короткий URL по его ID",
                "tags": [
                    "shorturls"
                ],
                "summary": "Удалить короткий URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID ShortURL",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ShortURL удалён",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "ShortURL не найден",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/shorturls": {
            "get": {
                "description": "Возвращает список всех коротких ссылок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shorturls"
                ],
                "summary": "Получить все короткие URL",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ShortURL"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении данных",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/stat/{id}": {
            "get": {
                "description": "Возвращает статистику просмотров для указанного ID пасты",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Получить статистику по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID статистики (равен ID пасты)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Stats"
                        }
                    },
                    "400": {
                        "description": "ID отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Статистика не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет статистику просмотров по ID пасты",
                "tags": [
                    "stats"
                ],
                "summary": "Удалить статистику",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID статистики (равен ID пасты)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Статистика удалена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "ID отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Статистика не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "description": "Возвращает список всех записей статистики просмотров",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Получить всю статистику",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Stats"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт пустую запись статистики. Используется редко, т.к. обычно статистика создаётся автоматически.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Создать новую запись статистики",
                "parameters": [
                    {
                        "description": "Пустой объект запроса",
                        "name": "stats",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateStatsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Stats"
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user": {
            "post": {
                "description": "Регистрирует нового пользователя с указанным именем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать нового пользователя",
                "parameters": [
                    {
                        "description": "Тело запроса с данными пользователя",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON или пустое имя",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при создании",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/{id}": {
            "get": {
                "description": "Возвращает пользователя по его уникальному ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос (отсутствует ID)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет пользователя по его ID",
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь успешно удалён",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос (отсутствует ID)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "Возвращает список всех зарегистрированных пользователей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить всех пользователей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера при получении пользователей",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s/{code}": {
            "get": {
                "description": "Возвращает содержимое пасты по короткому коду (короткому URL). Также увеличивает счётчик просмотров.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shorturls"
                ],
                "summary": "Получить пасту по короткой ссылке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Короткий код",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Контент пасты",
                        "schema": {
                            "$ref": "#/definitions/handlers.ContentResponse"
                        }
                    },
                    "400": {
                        "description": "Код отсутствует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "ShortURL или паста не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ContentResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "handlers.CreatePasteRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                }
            }
        },
        "handlers.CreateStatsRequest": {
            "type": "object"
        },
        "handlers.CreateUserRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.PasteCreateResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "short_url": {
                    "type": "string"
                }
            }
        },
        "model.Paste": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "model.ShortURL": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "original": {
                    "type": "string"
                }
            }
        },
        "model.Stats": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Pastebin API",
	Description:      "API для управления пастами, пользователями, статистикой и короткими URL",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
