// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/pb/pastebin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Paste struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paste) Reset() {
	*x = Paste{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paste) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paste) ProtoMessage() {}

func (x *Paste) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paste.ProtoReflect.Descriptor instead.
func (*Paste) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{0}
}

func (x *Paste) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Paste) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Paste) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Paste) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Paste) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PasteId       string                 `protobuf:"bytes,2,opt,name=paste_id,json=pasteId,proto3" json:"paste_id,omitempty"`
	Views         int64                  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stats) GetPasteId() string {
	if x != nil {
		return x.PasteId
	}
	return ""
}

func (x *Stats) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

type ShortURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortCode     string                 `protobuf:"bytes,3,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{3}
}

func (x *ShortURL) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShortURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortURL) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{4}
}

func (x *IDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IDRequestInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequestInt) Reset() {
	*x = IDRequestInt{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequestInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequestInt) ProtoMessage() {}

func (x *IDRequestInt) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequestInt.ProtoReflect.Descriptor instead.
func (*IDRequestInt) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{5}
}

func (x *IDRequestInt) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{6}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_internal_pb_pastebin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_pastebin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_internal_pb_pastebin_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_pb_pastebin_proto protoreflect.FileDescriptor

const file_internal_pb_pastebin_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/pb/pastebin.proto\x12\bpastebin\"\x7f\n" +
	"\x05Paste\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"d\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"H\n" +
	"\x05Stats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bpaste_id\x18\x02 \x01(\tR\apasteId\x12\x14\n" +
	"\x05views\x18\x03 \x01(\x03R\x05views\"\\\n" +
	"\bShortURL\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"short_code\x18\x03 \x01(\tR\tshortCode\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fIDRequestInt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\a\n" +
	"\x05Empty\"\"\n" +
	"\x06Status\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8a\x02\n" +
	"\fPasteService\x12/\n" +
	"\vCreatePaste\x12\x0f.pastebin.Paste\x1a\x0f.pastebin.Paste\x120\n" +
	"\bGetPaste\x12\x13.pastebin.IDRequest\x1a\x0f.pastebin.Paste\x120\n" +
	"\n" +
	"ListPastes\x12\x0f.pastebin.Empty\x1a\x0f.pastebin.Paste0\x01\x12/\n" +
	"\vUpdatePaste\x12\x0f.pastebin.Paste\x1a\x0f.pastebin.Paste\x124\n" +
	"\vDeletePaste\x12\x13.pastebin.IDRequest\x1a\x10.pastebin.Status2\x84\x02\n" +
	"\vUserService\x12,\n" +
	"\n" +
	"CreateUser\x12\x0e.pastebin.User\x1a\x0e.pastebin.User\x121\n" +
	"\aGetUser\x12\x16.pastebin.IDRequestInt\x1a\x0e.pastebin.User\x12.\n" +
	"\tListUsers\x12\x0f.pastebin.Empty\x1a\x0e.pastebin.User0\x01\x12,\n" +
	"\n" +
	"UpdateUser\x12\x0e.pastebin.User\x1a\x0e.pastebin.User\x126\n" +
	"\n" +
	"DeleteUser\x12\x16.pastebin.IDRequestInt\x1a\x10.pastebin.Status2\x8a\x02\n" +
	"\fStatsService\x12/\n" +
	"\vCreateStats\x12\x0f.pastebin.Stats\x1a\x0f.pastebin.Stats\x120\n" +
	"\bGetStats\x12\x13.pastebin.IDRequest\x1a\x0f.pastebin.Stats\x12/\n" +
	"\tListStats\x12\x0f.pastebin.Empty\x1a\x0f.pastebin.Stats0\x01\x120\n" +
	"\vUpdateStats\x12\x0f.pastebin.Stats\x1a\x10.pastebin.Status\x124\n" +
	"\vDeleteStats\x12\x13.pastebin.IDRequest\x1a\x10.pastebin.Status2\xac\x02\n" +
	"\x0fShortURLService\x128\n" +
	"\x0eCreateShortURL\x12\x12.pastebin.ShortURL\x1a\x12.pastebin.ShortURL\x126\n" +
	"\vGetShortURL\x12\x13.pastebin.IDRequest\x1a\x12.pastebin.ShortURL\x126\n" +
	"\rListShortURLs\x12\x0f.pastebin.Empty\x1a\x12.pastebin.ShortURL0\x01\x126\n" +
	"\x0eUpdateShortURL\x12\x12.pastebin.ShortURL\x1a\x10.pastebin.Status\x127\n" +
	"\x0eDeleteShortURL\x12\x13.pastebin.IDRequest\x1a\x10.pastebin.StatusB3Z1github.com/GritsyukLeonid/pastebin-go/internal/pbb\x06proto3"

var (
	file_internal_pb_pastebin_proto_rawDescOnce sync.Once
	file_internal_pb_pastebin_proto_rawDescData []byte
)

func file_internal_pb_pastebin_proto_rawDescGZIP() []byte {
	file_internal_pb_pastebin_proto_rawDescOnce.Do(func() {
		file_internal_pb_pastebin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_pastebin_proto_rawDesc), len(file_internal_pb_pastebin_proto_rawDesc)))
	})
	return file_internal_pb_pastebin_proto_rawDescData
}

var file_internal_pb_pastebin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_pb_pastebin_proto_goTypes = []any{
	(*Paste)(nil),        // 0: pastebin.Paste
	(*User)(nil),         // 1: pastebin.User
	(*Stats)(nil),        // 2: pastebin.Stats
	(*ShortURL)(nil),     // 3: pastebin.ShortURL
	(*IDRequest)(nil),    // 4: pastebin.IDRequest
	(*IDRequestInt)(nil), // 5: pastebin.IDRequestInt
	(*Empty)(nil),        // 6: pastebin.Empty
	(*Status)(nil),       // 7: pastebin.Status
}
var file_internal_pb_pastebin_proto_depIdxs = []int32{
	0,  // 0: pastebin.PasteService.CreatePaste:input_type -> pastebin.Paste
	4,  // 1: pastebin.PasteService.GetPaste:input_type -> pastebin.IDRequest
	6,  // 2: pastebin.PasteService.ListPastes:input_type -> pastebin.Empty
	0,  // 3: pastebin.PasteService.UpdatePaste:input_type -> pastebin.Paste
	4,  // 4: pastebin.PasteService.DeletePaste:input_type -> pastebin.IDRequest
	1,  // 5: pastebin.UserService.CreateUser:input_type -> pastebin.User
	5,  // 6: pastebin.UserService.GetUser:input_type -> pastebin.IDRequestInt
	6,  // 7: pastebin.UserService.ListUsers:input_type -> pastebin.Empty
	1,  // 8: pastebin.UserService.UpdateUser:input_type -> pastebin.User
	5,  // 9: pastebin.UserService.DeleteUser:input_type -> pastebin.IDRequestInt
	2,  // 10: pastebin.StatsService.CreateStats:input_type -> pastebin.Stats
	4,  // 11: pastebin.StatsService.GetStats:input_type -> pastebin.IDRequest
	6,  // 12: pastebin.StatsService.ListStats:input_type -> pastebin.Empty
	2,  // 13: pastebin.StatsService.UpdateStats:input_type -> pastebin.Stats
	4,  // 14: pastebin.StatsService.DeleteStats:input_type -> pastebin.IDRequest
	3,  // 15: pastebin.ShortURLService.CreateShortURL:input_type -> pastebin.ShortURL
	4,  // 16: pastebin.ShortURLService.GetShortURL:input_type -> pastebin.IDRequest
	6,  // 17: pastebin.ShortURLService.ListShortURLs:input_type -> pastebin.Empty
	3,  // 18: pastebin.ShortURLService.UpdateShortURL:input_type -> pastebin.ShortURL
	4,  // 19: pastebin.ShortURLService.DeleteShortURL:input_type -> pastebin.IDRequest
	0,  // 20: pastebin.PasteService.CreatePaste:output_type -> pastebin.Paste
	0,  // 21: pastebin.PasteService.GetPaste:output_type -> pastebin.Paste
	0,  // 22: pastebin.PasteService.ListPastes:output_type -> pastebin.Paste
	0,  // 23: pastebin.PasteService.UpdatePaste:output_type -> pastebin.Paste
	7,  // 24: pastebin.PasteService.DeletePaste:output_type -> pastebin.Status
	1,  // 25: pastebin.UserService.CreateUser:output_type -> pastebin.User
	1,  // 26: pastebin.UserService.GetUser:output_type -> pastebin.User
	1,  // 27: pastebin.UserService.ListUsers:output_type -> pastebin.User
	1,  // 28: pastebin.UserService.UpdateUser:output_type -> pastebin.User
	7,  // 29: pastebin.UserService.DeleteUser:output_type -> pastebin.Status
	2,  // 30: pastebin.StatsService.CreateStats:output_type -> pastebin.Stats
	2,  // 31: pastebin.StatsService.GetStats:output_type -> pastebin.Stats
	2,  // 32: pastebin.StatsService.ListStats:output_type -> pastebin.Stats
	7,  // 33: pastebin.StatsService.UpdateStats:output_type -> pastebin.Status
	7,  // 34: pastebin.StatsService.DeleteStats:output_type -> pastebin.Status
	3,  // 35: pastebin.ShortURLService.CreateShortURL:output_type -> pastebin.ShortURL
	3,  // 36: pastebin.ShortURLService.GetShortURL:output_type -> pastebin.ShortURL
	3,  // 37: pastebin.ShortURLService.ListShortURLs:output_type -> pastebin.ShortURL
	7,  // 38: pastebin.ShortURLService.UpdateShortURL:output_type -> pastebin.Status
	7,  // 39: pastebin.ShortURLService.DeleteShortURL:output_type -> pastebin.Status
	20, // [20:40] is the sub-list for method output_type
	0,  // [0:20] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_pastebin_proto_init() }
func file_internal_pb_pastebin_proto_init() {
	if File_internal_pb_pastebin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_pastebin_proto_rawDesc), len(file_internal_pb_pastebin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_internal_pb_pastebin_proto_goTypes,
		DependencyIndexes: file_internal_pb_pastebin_proto_depIdxs,
		MessageInfos:      file_internal_pb_pastebin_proto_msgTypes,
	}.Build()
	File_internal_pb_pastebin_proto = out.File
	file_internal_pb_pastebin_proto_goTypes = nil
	file_internal_pb_pastebin_proto_depIdxs = nil
}
